# -*- coding: utf-8 -*-
"""Untitled88.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxHyTlJj7Ew2tg-nlO11wLGSCrDqSeLF
"""

number=5
if number == 1:
  print("one")
elif number == 2:
  print("two")
elif number == 3:
  print("three")
else:
  print("unknown")